apiVersion: v1
kind: Service
metadata:
  labels:
    app: bucketlist-stateful
  name: bucketlist-stateful
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bucketlist-stateful
  type: LoadBalancer
status:
  loadBalancer: {}
